# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LvMP-Mac' do
pod 'Socket.IO-Client-Swift', '~> 13.3.0'
pod 'Alamofire'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LvMP-Mac

end
